[build]
  command = "ng build --configuration=production"
  publish = "dist/mas-latino"  # Reemplaza con tu ruta final de salida

[[plugins]]
  package = "netlify-plugin-prerender"

  [plugins.inputs]
  prerenderToken = "rDjdSfG9AiLjP4fYB9Xd" 
